/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: example.i

package example

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
extern void _wrap_Swig_free_example_031f8a7e70ef1b78(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_example_031f8a7e70ef1b78(swig_intgo arg1);
extern double _wrap_AREA_example_031f8a7e70ef1b78(void);
extern double _wrap_LENGTH_example_031f8a7e70ef1b78(void);
extern swig_intgo _wrap_gcd_example_031f8a7e70ef1b78(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_Dvar_set_example_031f8a7e70ef1b78(double arg1);
extern double _wrap_Dvar_get_example_031f8a7e70ef1b78(void);
extern void _wrap_status_set_example_031f8a7e70ef1b78(swig_intgo arg1);
extern swig_intgo _wrap_status_get_example_031f8a7e70ef1b78(void);
extern void _wrap_path_set_example_031f8a7e70ef1b78(swig_type_1 arg1);
extern swig_type_2 _wrap_path_get_example_031f8a7e70ef1b78(void);
extern void _wrap_print_vars_example_031f8a7e70ef1b78(void);
extern void _wrap_iptrvar_set_example_031f8a7e70ef1b78(swig_voidp arg1);
extern swig_voidp _wrap_iptrvar_get_example_031f8a7e70ef1b78(void);
extern swig_voidp _wrap_new_int_example_031f8a7e70ef1b78(swig_intgo arg1);
extern void _wrap_ptptr_set_example_031f8a7e70ef1b78(uintptr_t arg1);
extern uintptr_t _wrap_ptptr_get_example_031f8a7e70ef1b78(void);
extern uintptr_t _wrap_new_Point_example_031f8a7e70ef1b78(swig_intgo arg1, swig_intgo arg2);
extern swig_type_3 _wrap_point_Print_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_Point_x_set_example_031f8a7e70ef1b78(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Point_x_get_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_Point_y_set_example_031f8a7e70ef1b78(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Point_y_get_example_031f8a7e70ef1b78(uintptr_t arg1);
extern swig_intgo _wrap_RED_example_031f8a7e70ef1b78(void);
extern swig_intgo _wrap_BLUE_example_031f8a7e70ef1b78(void);
extern swig_intgo _wrap_GREEN_example_031f8a7e70ef1b78(void);
extern uintptr_t _wrap_new_Foo_example_031f8a7e70ef1b78(void);
extern swig_intgo _wrap_IMPULSE_Foo_example_031f8a7e70ef1b78(void);
extern swig_intgo _wrap_WARP_Foo_example_031f8a7e70ef1b78(void);
extern swig_intgo _wrap_LUDICROUS_Foo_example_031f8a7e70ef1b78(void);
extern void _wrap_Foo_enum_test_example_031f8a7e70ef1b78(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_delete_Foo_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_enum_test_example_031f8a7e70ef1b78(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_delete_Shape_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_Shape_x_set_example_031f8a7e70ef1b78(uintptr_t arg1, double arg2);
extern double _wrap_Shape_x_get_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_Shape_y_set_example_031f8a7e70ef1b78(uintptr_t arg1, double arg2);
extern double _wrap_Shape_y_get_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_Shape_move_example_031f8a7e70ef1b78(uintptr_t arg1, double arg2, double arg3);
extern double _wrap_Shape_area_example_031f8a7e70ef1b78(uintptr_t arg1);
extern double _wrap_Shape_perimeter_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_Shape_nshapes_set_example_031f8a7e70ef1b78(swig_intgo arg1);
extern swig_intgo _wrap_Shape_nshapes_get_example_031f8a7e70ef1b78(void);
extern uintptr_t _wrap_new_Circle_example_031f8a7e70ef1b78(double arg1);
extern double _wrap_Circle_area_example_031f8a7e70ef1b78(uintptr_t arg1);
extern double _wrap_Circle_perimeter_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_delete_Circle_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_SetCircle_X_example_031f8a7e70ef1b78(uintptr_t _swig_base, double arg1);
extern double _wrap_GetCircle_X_example_031f8a7e70ef1b78(uintptr_t _swig_base);
extern void _wrap_SetCircle_Y_example_031f8a7e70ef1b78(uintptr_t _swig_base, double arg1);
extern double _wrap_GetCircle_Y_example_031f8a7e70ef1b78(uintptr_t _swig_base);
extern void _wrap_Circle_move_example_031f8a7e70ef1b78(uintptr_t _swig_base, double arg1, double arg2);
extern uintptr_t _wrap_new_Square_example_031f8a7e70ef1b78(double arg1);
extern double _wrap_Square_area_example_031f8a7e70ef1b78(uintptr_t arg1);
extern double _wrap_Square_perimeter_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_delete_Square_example_031f8a7e70ef1b78(uintptr_t arg1);
extern void _wrap_SetSquare_X_example_031f8a7e70ef1b78(uintptr_t _swig_base, double arg1);
extern double _wrap_GetSquare_X_example_031f8a7e70ef1b78(uintptr_t _swig_base);
extern void _wrap_SetSquare_Y_example_031f8a7e70ef1b78(uintptr_t _swig_base, double arg1);
extern double _wrap_GetSquare_Y_example_031f8a7e70ef1b78(uintptr_t _swig_base);
extern void _wrap_Square_move_example_031f8a7e70ef1b78(uintptr_t _swig_base, double arg1, double arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const PI float64 = 3.14159265358979323846
const ICONST int = 42
const SCONST string = "Hello World"
func _swig_getAREA() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_AREA_example_031f8a7e70ef1b78())
	return swig_r
}

var AREA float64 = _swig_getAREA()
func _swig_getLENGTH() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_LENGTH_example_031f8a7e70ef1b78())
	return swig_r
}

var LENGTH float64 = _swig_getLENGTH()
const Iconst int = 37
const Fconst float64 = 3.14
func Gcd(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_gcd_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func SetDvar(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_Dvar_set_example_031f8a7e70ef1b78(C.double(_swig_i_0))
}

func GetDvar() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_Dvar_get_example_031f8a7e70ef1b78())
	return swig_r
}

func SetStatus(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_status_set_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0))
}

func GetStatus() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_status_get_example_031f8a7e70ef1b78())
	return swig_r
}

func SetPath(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_path_set_example_031f8a7e70ef1b78(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func GetPath() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_path_get_example_031f8a7e70ef1b78()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Print_vars() {
	C._wrap_print_vars_example_031f8a7e70ef1b78()
}

func SetIptrvar(arg1 *int) {
	_swig_i_0 := arg1
	C._wrap_iptrvar_set_example_031f8a7e70ef1b78(C.swig_voidp(_swig_i_0))
}

func GetIptrvar() (_swig_ret *int) {
	var swig_r *int
	swig_r = (*int)(C._wrap_iptrvar_get_example_031f8a7e70ef1b78())
	return swig_r
}

func New_int(arg1 int) (_swig_ret *int) {
	var swig_r *int
	_swig_i_0 := arg1
	swig_r = (*int)(C._wrap_new_int_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func SetPtptr(arg1 Point) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_ptptr_set_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
}

func GetPtptr() (_swig_ret Point) {
	var swig_r Point
	swig_r = (Point)(SwigcptrPoint(C._wrap_ptptr_get_example_031f8a7e70ef1b78()))
	return swig_r
}

func New_Point(arg1 int, arg2 int) (_swig_ret Point) {
	var swig_r Point
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Point)(SwigcptrPoint(C._wrap_new_Point_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func Point_Print(arg1 Point) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_point_Print_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

type SwigcptrPoint uintptr

func (p SwigcptrPoint) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPoint) SwigIsPoint() {
}

func (arg1 SwigcptrPoint) SetX(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Point_x_set_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint) GetX() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Point_x_get_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrPoint) SetY(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Point_y_set_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint) GetY() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Point_y_get_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type Point interface {
	Swigcptr() uintptr
	SwigIsPoint()
	SetX(arg2 int)
	GetX() (_swig_ret int)
	SetY(arg2 int)
	GetY() (_swig_ret int)
}

type Color int
func _swig_getRED() (_swig_ret Color) {
	var swig_r Color
	swig_r = (Color)(C._wrap_RED_example_031f8a7e70ef1b78())
	return swig_r
}

var RED Color = _swig_getRED()
func _swig_getBLUE() (_swig_ret Color) {
	var swig_r Color
	swig_r = (Color)(C._wrap_BLUE_example_031f8a7e70ef1b78())
	return swig_r
}

var BLUE Color = _swig_getBLUE()
func _swig_getGREEN() (_swig_ret Color) {
	var swig_r Color
	swig_r = (Color)(C._wrap_GREEN_example_031f8a7e70ef1b78())
	return swig_r
}

var GREEN Color = _swig_getGREEN()
type SwigcptrFoo uintptr

func (p SwigcptrFoo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFoo) SwigIsFoo() {
}

func NewFoo() (_swig_ret Foo) {
	var swig_r Foo
	swig_r = (Foo)(SwigcptrFoo(C._wrap_new_Foo_example_031f8a7e70ef1b78()))
	return swig_r
}

type FooSpeed int
func _swig_getFoo_IMPULSE_Foo() (_swig_ret FooSpeed) {
	var swig_r FooSpeed
	swig_r = (FooSpeed)(C._wrap_IMPULSE_Foo_example_031f8a7e70ef1b78())
	return swig_r
}

var FooIMPULSE FooSpeed = _swig_getFoo_IMPULSE_Foo()
func _swig_getFoo_WARP_Foo() (_swig_ret FooSpeed) {
	var swig_r FooSpeed
	swig_r = (FooSpeed)(C._wrap_WARP_Foo_example_031f8a7e70ef1b78())
	return swig_r
}

var FooWARP FooSpeed = _swig_getFoo_WARP_Foo()
func _swig_getFoo_LUDICROUS_Foo() (_swig_ret FooSpeed) {
	var swig_r FooSpeed
	swig_r = (FooSpeed)(C._wrap_LUDICROUS_Foo_example_031f8a7e70ef1b78())
	return swig_r
}

var FooLUDICROUS FooSpeed = _swig_getFoo_LUDICROUS_Foo()
func (arg1 SwigcptrFoo) Enum_test(arg2 FooSpeed) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Foo_enum_test_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func DeleteFoo(arg1 Foo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Foo_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
}

type Foo interface {
	Swigcptr() uintptr
	SwigIsFoo()
	Enum_test(arg2 FooSpeed)
}

func Enum_test(arg1 Color, arg2 FooSpeed) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_enum_test_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

type SwigcptrShape uintptr

func (p SwigcptrShape) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrShape) SwigIsShape() {
}

func DeleteShape(arg1 Shape) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Shape_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrShape) SetX(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Shape_x_set_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrShape) GetX() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Shape_x_get_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShape) SetY(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Shape_y_set_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrShape) GetY() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Shape_y_get_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShape) Move(arg2 float64, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Shape_move_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2))
}

func (arg1 SwigcptrShape) Area() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Shape_area_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShape) Perimeter() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Shape_perimeter_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func SetShapeNshapes(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_Shape_nshapes_set_example_031f8a7e70ef1b78(C.swig_intgo(_swig_i_0))
}

func GetShapeNshapes() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_Shape_nshapes_get_example_031f8a7e70ef1b78())
	return swig_r
}

type Shape interface {
	Swigcptr() uintptr
	SwigIsShape()
	SetX(arg2 float64)
	GetX() (_swig_ret float64)
	SetY(arg2 float64)
	GetY() (_swig_ret float64)
	Move(arg2 float64, arg3 float64)
	Area() (_swig_ret float64)
	Perimeter() (_swig_ret float64)
}

type SwigcptrCircle uintptr

func (p SwigcptrCircle) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCircle) SwigIsCircle() {
}

func NewCircle(arg1 float64) (_swig_ret Circle) {
	var swig_r Circle
	_swig_i_0 := arg1
	swig_r = (Circle)(SwigcptrCircle(C._wrap_new_Circle_example_031f8a7e70ef1b78(C.double(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrCircle) Area() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Circle_area_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrCircle) Perimeter() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Circle_perimeter_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteCircle(arg1 Circle) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Circle_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrCircle) SetX(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_SetCircle_X_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base), C.double(_swig_i_0))
}

func (_swig_base SwigcptrCircle) GetX() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_GetCircle_X_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base)))
	return swig_r
}

func (_swig_base SwigcptrCircle) SetY(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_SetCircle_Y_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base), C.double(_swig_i_0))
}

func (_swig_base SwigcptrCircle) GetY() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_GetCircle_Y_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base)))
	return swig_r
}

func (_swig_base SwigcptrCircle) Move(arg1 float64, arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Circle_move_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base), C.double(_swig_i_0), C.double(_swig_i_1))
}

func (p SwigcptrCircle) SwigIsShape() {
}

func (p SwigcptrCircle) SwigGetShape() Shape {
	return SwigcptrShape(p.Swigcptr())
}

type Circle interface {
	Swigcptr() uintptr
	SwigIsCircle()
	Area() (_swig_ret float64)
	Perimeter() (_swig_ret float64)
	SetX(arg1 float64)
	GetX() (_swig_ret float64)
	SetY(arg1 float64)
	GetY() (_swig_ret float64)
	Move(arg1 float64, arg2 float64)
	SwigIsShape()
	SwigGetShape() Shape
}

type SwigcptrSquare uintptr

func (p SwigcptrSquare) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSquare) SwigIsSquare() {
}

func NewSquare(arg1 float64) (_swig_ret Square) {
	var swig_r Square
	_swig_i_0 := arg1
	swig_r = (Square)(SwigcptrSquare(C._wrap_new_Square_example_031f8a7e70ef1b78(C.double(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSquare) Area() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Square_area_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSquare) Perimeter() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_Square_perimeter_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteSquare(arg1 Square) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Square_example_031f8a7e70ef1b78(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrSquare) SetX(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_SetSquare_X_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base), C.double(_swig_i_0))
}

func (_swig_base SwigcptrSquare) GetX() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_GetSquare_X_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base)))
	return swig_r
}

func (_swig_base SwigcptrSquare) SetY(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_SetSquare_Y_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base), C.double(_swig_i_0))
}

func (_swig_base SwigcptrSquare) GetY() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_GetSquare_Y_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base)))
	return swig_r
}

func (_swig_base SwigcptrSquare) Move(arg1 float64, arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Square_move_example_031f8a7e70ef1b78(C.uintptr_t(_swig_base), C.double(_swig_i_0), C.double(_swig_i_1))
}

func (p SwigcptrSquare) SwigIsShape() {
}

func (p SwigcptrSquare) SwigGetShape() Shape {
	return SwigcptrShape(p.Swigcptr())
}

type Square interface {
	Swigcptr() uintptr
	SwigIsSquare()
	Area() (_swig_ret float64)
	Perimeter() (_swig_ret float64)
	SetX(arg1 float64)
	GetX() (_swig_ret float64)
	SetY(arg1 float64)
	GetY() (_swig_ret float64)
	Move(arg1 float64, arg2 float64)
	SwigIsShape()
	SwigGetShape() Shape
}


